export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Projects } from './Projects'
export { default as Experience } from './Experience'
export { default as NavigationDots } from './NavigationDots'
export { default as SocialMediaIcons } from './SocialMediaIcons'